# Generated by Django 3.2.6 on 2023-05-12 18:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('primary_phone', models.CharField(max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('map_link', models.URLField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('shown_in_website', models.BooleanField(default=True)),
                ('off_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=50), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
